language:
    - cpp

compiler:
    - g++
    - clang

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    - kalakris-cmake
    packages:
    - gcc-4.9
    - g++-4.9
    - libboost1.55-all-dev
    - libssl-dev
    - cmake

before_script:
    - git clone --depth=1 https://github.com/ipkn/crow.git crow/repo
    - git clone --depth=1 https://github.com/zaphoyd/websocketpp.git websocketpp/repo
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

script:
    - mkdir build
    - cd build
    - cmake .. -DEXT_HEADERS_FROM_SOURCE=ON
    - make
